# Primera etapa: Construir la aplicación
FROM alpine:latest as build

RUN apk update
RUN apk add openjdk17

WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew bootJar --no-daemon

# Segunda etapa: Ejecutar la aplicación
FROM openjdk:17-alpine

WORKDIR /app
EXPOSE 9000
COPY --from=build /app/build/libs/APIRest-0.0.1-SNAPSHOT.jar ./app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
